import {createExport, fetchTask, fetchTaskResults} from "../api.js";
import {renderWorkflowProgress} from "./progress.js";
import {appState, setTask, setTaskResults} from "../state.js";
import {formatBytes} from "../shared/format.js";

// Map correction keys from analysis_config to output slugs that become available
const CORRECTION_TO_SLUGS = {
  diurnal: ["corrected_field"],
  igrf: ["corrected_field"],
  spike: ["corrected_field"],
  lag: ["corrected_field"],
  heading: ["corrected_field"],
  level: ["corrected_field"],
  micro_leveling: ["corrected_field"],
  fft: ["filtered_surface"],
  upward_continuation: ["upward_continuation"],
  downward_continuation: ["downward_continuation"],
  regional: ["regional_field", "residual_field"],
  rtp: ["rtp"],
};

const CARD_TO_FORMAT = {
  "ec-pdf": "pdf",
  "ec-pptx": "pptx",
  "ec-word": "word",
  "ec-geojson": "geojson",
  "ec-kml": "kmz",
  "ec-csv": "csv",
  "ec-gdb": "gdb",
  "ec-png": "png",
};

const OUTPUT_DEFINITIONS = [
  {
    slug: "corrected_field",
    label: "Corrected Magnetic Field",
    description: "Primary corrected field map and its companion visuals.",
    available: (results) => Boolean(results?.surface || results?.corrected_field),
    defaultSelected: true,
  },
  {
    slug: "regional_field",
    label: "Regional Magnetic Field",
    description: "Long-wavelength background field separated from the corrected surface.",
    available: (results) => Boolean(results?.regional_field || results?.regional_surface),
    defaultSelected: true,
  },
  {
    slug: "residual_field",
    label: "Residual Magnetic Field",
    description: "Local anomaly-focused field after regional separation.",
    available: (results) => Boolean(results?.regional_residual || results?.residual_surface || results?.emag2_residual),
    defaultSelected: true,
  },
  {
    slug: "rtp",
    label: "Reduction to Pole (RTP)",
    description: "Pole-reduced or low-latitude fallback transform if available.",
    available: (results) => Boolean(results?.rtp_surface),
    defaultSelected: false,
  },
  {
    slug: "analytic_signal",
    label: "Analytic Signal",
    description: "Edge-strength layer for anomaly footprint screening.",
    available: (results) => Boolean(results?.analytic_signal),
    defaultSelected: false,
  },
  {
    slug: "tilt_derivative",
    label: "Tilt Derivative",
    description: "Tilt-based edge and contrast enhancement layer.",
    available: (results) => Boolean(results?.tilt_derivative),
    defaultSelected: false,
  },
  {
    slug: "total_gradient",
    label: "Total Gradient",
    description: "Combined gradient magnitude where generated.",
    available: (results) => Boolean(results?.total_gradient),
    defaultSelected: false,
  },
  {
    slug: "fvd",
    label: "First Vertical Derivative",
    description: "Short-wavelength sharpening layer for near-surface contrast.",
    available: (results) => Boolean(results?.first_vertical_derivative),
    defaultSelected: false,
  },
  {
    slug: "hd",
    label: "Horizontal Derivative",
    description: "Lateral boundary emphasis for anomaly edges.",
    available: (results) => Boolean(results?.horizontal_derivative),
    defaultSelected: false,
  },
  {
    slug: "uncertainty",
    label: "Uncertainty Surface",
    description: "Support and reliability surface for confidence framing.",
    available: (results) => Boolean(results?.uncertainty),
    defaultSelected: false,
  },
  {
    slug: "filtered_surface",
    label: "Filtered Surface",
    description: "Filtered magnetic product if it was generated by the run.",
    available: (results) => Boolean(results?.filtered_surface),
    defaultSelected: false,
  },
  {
    slug: "upward_continuation",
    label: "Upward Continuation",
    description: "Higher-altitude smoothed continuation output.",
    available: (results) => Boolean(results?.upward_continuation),
    defaultSelected: false,
  },
  {
    slug: "downward_continuation",
    label: "Downward Continuation",
    description: "Lower-altitude continuation output where generated.",
    available: (results) => Boolean(results?.downward_continuation),
    defaultSelected: false,
  },
  {
    slug: "regional_residual_product",
    label: "Regional Residual Product",
    description: "Additional regional-residual comparison layer.",
    available: (results) => Boolean(results?.emag2_residual),
    defaultSelected: false,
  },
  {
    slug: "line_profiles",
    label: "Line Profiles",
    description: "Measured and predicted profile traces along the survey path.",
    available: (results) => Boolean((results?.points || []).length || (results?.predicted_points || []).length),
    defaultSelected: false,
  },
];

const NARRATIVE_DEFINITIONS = [
  {
    key: "anomaly_catalogue",
    label: "Anomaly catalogue",
    optionKey: "include_anomaly_catalogue",
    description: "Tabulate anomaly zones when anomaly-supporting outputs exist.",
    available: (results, outputs) => Boolean(results?.anomaly_catalogue_b64 || results?.anomalies || outputs.some((item) => item.slug === "residual_field")),
    defaultSelected: false,
  },
  {
    key: "structural_interpretation",
    label: "Structural interpretation",
    optionKey: "include_structural_interpretation",
    description: "Include structural screening when residual or derivative layers exist.",
    available: (_results, outputs) => outputs.some((item) => ["residual_field", "analytic_signal", "fvd", "hd", "tilt_derivative"].includes(item.slug)),
    defaultSelected: true,
  },
  {
    key: "coverage_gap_analysis",
    label: "Coverage gap analysis",
    optionKey: "include_coverage_gap_analysis",
    description: "Describe support gaps when uncertainty or support-limited outputs exist.",
    available: (results) => Boolean(results?.uncertainty || results?.model_metadata || results?.support_mask),
    defaultSelected: false,
  },
  {
    key: "correction_report",
    label: "Correction report",
    optionKey: "include_correction_report",
    description: "Summarize applied corrections and fallback events from the run.",
    available: (results) => Boolean(results?.correction_report || results?.qa_report || results?.validation_summary),
    defaultSelected: true,
  },
  {
    key: "model_diagnostics",
    label: "Model diagnostics",
    optionKey: "include_model_diagnostics",
    description: "Include modelling metrics only when model metadata exists.",
    available: (results) => Boolean(results?.model_metadata),
    defaultSelected: false,
  },
  {
    key: "qa_summary",
    label: "QA summary",
    optionKey: "include_qa_summary",
    description: "Carry the run QA status, warnings, and fallback context into the report.",
    available: (results) => Boolean(results?.qa_report || results?.validation_summary),
    defaultSelected: true,
  },
];

function getRoots() {
  return {
    screen: document.getElementById("screen-export"),
    count: document.getElementById("exCnt"),
    progress: document.getElementById("exportProg"),
    done: document.getElementById("exportDone"),
  };
}

function ensureSelectionCards() {
  const anchor = document.getElementById("exportReportOptionsAnchor");
  if (!anchor) return {};
  let outputsCard = document.getElementById("exportOutputsCard");
  if (!outputsCard) {
    outputsCard = document.createElement("div");
    outputsCard.id = "exportOutputsCard";
    outputsCard.className = "card card-g";
    outputsCard.style.marginBottom = "14px";
    anchor.insertAdjacentElement("afterend", outputsCard);
  }
  let narrativeCard = document.getElementById("exportNarrativeCard");
  if (!narrativeCard) {
    narrativeCard = document.createElement("div");
    narrativeCard.id = "exportNarrativeCard";
    narrativeCard.className = "card card-sm";
    narrativeCard.style.marginBottom = "14px";
    outputsCard.insertAdjacentElement("afterend", narrativeCard);
  }
  outputsCard.innerHTML = `
    <div style="font-size:13px;font-weight:700;color:var(--text);margin-bottom:6px">Processed outputs for reports and presentations</div>
    <div style="font-size:10.5px;color:var(--text3);line-height:1.7;margin-bottom:11px">These are the outputs generated from your selected processing options. Uncheck any you don't want in the report.</div>
    <div id="exportOutputSelectionList" class="g2" style="gap:8px"></div>
  `;
  narrativeCard.innerHTML = `
    <div style="font-size:13px;font-weight:700;color:var(--text);margin-bottom:6px">Optional narrative sections</div>
    <div style="font-size:10.5px;color:var(--text3);line-height:1.7;margin-bottom:11px">These sections are only offered when the processed run has enough supporting evidence for them.</div>
    <div id="exportNarrativeSelectionList" class="g2" style="gap:8px"></div>
    <div id="exportNarrativeNote" style="display:none;font-size:10.5px;color:var(--g600);line-height:1.7;margin-top:10px"></div>
  `;
  return {
    outputsList: document.getElementById("exportOutputSelectionList"),
    narrativeList: document.getElementById("exportNarrativeSelectionList"),
    narrativeNote: document.getElementById("exportNarrativeNote"),
  };
}

function getSelectedFormats() {
  return Array.from(document.querySelectorAll("#screen-export .ec.on"))
    .map((card) => CARD_TO_FORMAT[card.id])
    .filter(Boolean);
}

function renderSelectionCount() {
  const formats = getSelectedFormats();
  getRoots().count.textContent = `${formats.length} format${formats.length === 1 ? "" : "s"} selected`;
}

function renderProgress(formats, artifacts = []) {
  const roots = getRoots();
  roots.progress.style.display = "block";
  const card = roots.progress.querySelector(".card");
  card.innerHTML = formats.map((format) => {
    const artifact = artifacts.find((item) => item.file_name.toLowerCase().includes(format.replace("kmz", "km")));
    return `
      <div class="eprow">
        <div class="epname">${format.toUpperCase()}</div>
        <div class="epbar"><div class="epfill" style="width:${artifact ? "100%" : "55%"};background:${artifact ? "var(--g500)" : "var(--amber)"}"></div></div>
        <div class="epsize">${artifact ? formatBytes(artifact.size_bytes) : "Building..."}</div>
        <span class="badge ${artifact ? "bg" : "bgr"}">${artifact ? "Completed" : "Running"}</span>
      </div>
    `;
  }).join("");
}

function renderDownloads(job) {
  const roots = getRoots();
  const artifacts = job?.details?.artifacts || [];
  roots.done.style.display = artifacts.length ? "block" : "none";
  roots.done.innerHTML = artifacts.length ? `
    <div class="sep">Download links</div>
    <div class="card card-g">
      <div style="display:flex;flex-direction:column;gap:12px">
        ${artifacts.map((artifact, index) => `
          <div style="${index ? "border-top:1px solid var(--g100);padding-top:11px;" : ""}display:flex;align-items:center;justify-content:space-between;gap:10px">
            <div>
              <div style="font-size:12.5px;font-weight:700;color:var(--text)">${artifact.file_name}</div>
              <div style="font-size:10.5px;color:var(--text3);margin-top:2px;font-family:'JetBrains Mono',monospace">${formatBytes(artifact.size_bytes)}  -  ${artifact.gcs_uri}</div>
            </div>
            <a class="btn btn-g btn-sm" href="${artifact.signed_url}" target="_blank" rel="noreferrer">Download</a>
          </div>
        `).join("")}
      </div>
    </div>
  ` : "";
}

function getAvailableOutputs(results) {
  // Only show outputs that were actually generated by the processing run
  // AND match what the user selected via corrections in analysis_config
  const appliedCorrections = (appState.task?.analysis_config?.corrections || []).map((c) => c.toLowerCase());
  const enabledSlugs = new Set();
  // Always include corrected_field as base output
  enabledSlugs.add("corrected_field");
  // Add slugs based on which corrections were applied
  for (const correction of appliedCorrections) {
    for (const [key, slugs] of Object.entries(CORRECTION_TO_SLUGS)) {
      if (correction.includes(key)) slugs.forEach((s) => enabledSlugs.add(s));
    }
  }
  // Always include analytic_signal, tilt_derivative, total_gradient, fvd, hd if they exist in results
  const derivativesSlugs = ["analytic_signal", "tilt_derivative", "total_gradient", "fvd", "hd", "uncertainty", "line_profiles"];
  return OUTPUT_DEFINITIONS
    .map((definition) => ({...definition, availableNow: definition.available(results)}))
    .filter((definition) => definition.availableNow && (enabledSlugs.has(definition.slug) || derivativesSlugs.includes(definition.slug)));
}

function getAvailableNarratives(results, outputs) {
  return NARRATIVE_DEFINITIONS
    .map((definition) => ({...definition, availableNow: definition.available(results, outputs)}))
    .filter((definition) => definition.availableNow);
}

function getSelectedOutputs() {
  return Array.from(document.querySelectorAll("[data-export-output].on")).map((node) => ({
    slug: node.dataset.exportOutput,
    label: node.dataset.exportLabel,
  }));
}

function getSelectedNarratives() {
  return Array.from(document.querySelectorAll("[data-export-section].on")).map((node) => ({
    key: node.dataset.exportSection,
    label: node.dataset.exportLabel,
    optionKey: node.dataset.optionKey,
  }));
}

function buildExportOptions(results) {
  const selectedOutputs = getSelectedOutputs();
  const selectedNarratives = getSelectedNarratives();
  const outputSlugs = selectedOutputs.map((item) => item.slug);
  const narrativeLabels = selectedNarratives.map((item) => item.label);
  return {
    include_corrected_field: outputSlugs.includes("corrected_field"),
    include_regional_field: outputSlugs.includes("regional_field"),
    include_residual_field: outputSlugs.includes("residual_field"),
    include_anomaly_catalogue: narrativeLabels.includes("Anomaly catalogue"),
    include_drilling_recommendations: narrativeLabels.includes("Drilling recommendations"),
    include_structural_interpretation: narrativeLabels.includes("Structural interpretation"),
    include_coverage_gap_analysis: narrativeLabels.includes("Coverage gap analysis"),
    include_correction_report: narrativeLabels.includes("Correction report"),
    include_model_diagnostics: narrativeLabels.includes("Model diagnostics"),
    include_qa_summary: narrativeLabels.includes("QA summary"),
    selected_output_slugs: outputSlugs,
    selected_output_labels: selectedOutputs.map((item) => item.label),
    selected_narrative_sections: narrativeLabels,
    available_layers: {
      corrected: Boolean(results?.surface || results?.corrected_field),
      regional: Boolean(results?.regional_field || results?.regional_surface),
      residual: Boolean(results?.regional_residual || results?.residual_surface || results?.emag2_residual),
      rtp: Boolean(results?.rtp_surface),
      analytic_signal: Boolean(results?.analytic_signal),
      tilt_derivative: Boolean(results?.tilt_derivative),
      total_gradient: Boolean(results?.total_gradient),
      first_vertical_derivative: Boolean(results?.first_vertical_derivative),
      horizontal_derivative: Boolean(results?.horizontal_derivative),
      uncertainty: Boolean(results?.uncertainty),
    },
  };
}

function selectionChipHtml({label, description, selected, dataset}) {
  const attrs = Object.entries(dataset)
    .map(([key, value]) => {
      const attrName = key.replace(/([A-Z])/g, "-$1").toLowerCase();
      return `data-${attrName}="${String(value).replace(/"/g, "&quot;")}"`;
    })
    .join(" ");
  return `
    <div class="chk ${selected ? "on" : ""}" ${attrs} style="margin-bottom:0;padding:9px 11px" onclick="toggleChk(this)">
      <div class="chk-box ${selected ? "on" : ""}">${selected ? "✓" : ""}</div>
      <div style="display:flex;flex-direction:column;gap:3px">
        <span class="chk-t" style="font-size:12px">${label}</span>
        <span style="font-size:10px;color:var(--text3);line-height:1.55">${description}</span>
      </div>
    </div>
  `;
}

function renderExportAvailability(results) {
  const extraRoots = ensureSelectionCards();
  if (!extraRoots.outputsList || !extraRoots.narrativeList) {
    return;
  }
  const outputs = getAvailableOutputs(results);
  const narratives = getAvailableNarratives(results, outputs);

  extraRoots.outputsList.innerHTML = outputs.length
    ? outputs.map((item) => selectionChipHtml({
      label: item.label,
      description: item.description,
      selected: true,
      dataset: {
        exportOutput: item.slug,
        exportLabel: item.label,
      },
    })).join("")
    : `<div style="font-size:10.5px;color:var(--text3);line-height:1.7">No processed result layers are currently available for report exports.</div>`;

  extraRoots.narrativeList.innerHTML = narratives.length
    ? narratives.map((item) => selectionChipHtml({
      label: item.label,
      description: item.description,
      selected: item.defaultSelected,
      dataset: {
        exportSection: item.key,
        exportLabel: item.label,
        optionKey: item.optionKey,
      },
    })).join("")
    : `<div style="font-size:10.5px;color:var(--text3);line-height:1.7">No optional narrative sections are supported by the current processed outputs.</div>`;

  const qaAvailable = narratives.some((item) => item.key === "qa_summary");
  if (extraRoots.narrativeNote) {
    extraRoots.narrativeNote.style.display = qaAvailable ? "block" : "none";
    extraRoots.narrativeNote.textContent = qaAvailable
      ? "QA summary and fallback honesty remain important even when you keep the narrative selection minimal."
      : "";
  }

}

export async function loadExportView() {
  renderSelectionCount();
  ensureSelectionCards();
  document.querySelectorAll("#screen-export .ec .badge.bgr").forEach((badge) => {
    if (/\d/.test(badge.textContent)) {
      badge.remove();
    }
  });
  const sizeNodes = document.querySelectorAll("#exportProg .epsize");
  sizeNodes.forEach((node) => {
    node.textContent = "—";
  });
  if (!appState.project || !appState.task) {
    getRoots().done.style.display = "none";
    getRoots().progress.style.display = "none";
    throw new Error("Run a processed task before opening Export.");
  }
  const task = await fetchTask(appState.project.id, appState.task.id);
  setTask(task);
  renderWorkflowProgress();
  let results = appState.taskResults;
  if (!results && task.results?.artifacts?.length) {
    try {
      results = await fetchTaskResults(appState.project.id, appState.task.id);
      setTaskResults(results);
    } catch (_error) {
      results = null;
    }
  }
  renderExportAvailability(results);
  const latestJob = (task.export_jobs || []).slice(-1)[0];
  if (latestJob) {
    renderProgress(latestJob.formats || [], latestJob.details?.artifacts || []);
    renderDownloads(latestJob);
  } else {
    getRoots().progress.style.display = "none";
    getRoots().done.style.display = "none";
  }
}

export async function runExport() {
  if (!appState.task) {
    throw new Error("Run processing before creating exports.");
  }
  const formats = getSelectedFormats();
  if (!formats.length) {
    throw new Error("Choose at least one export format.");
  }
  const selectedOutputs = getSelectedOutputs();
  const reportFormats = formats.filter((format) => ["pdf", "pptx", "word"].includes(format));
  if (reportFormats.length && !selectedOutputs.length) {
    throw new Error("Choose at least one processed output for the report exports.");
  }
  renderProgress(formats, []);
  const selectedNarratives = getSelectedNarratives();
  const exportOptions = buildExportOptions(appState.taskResults || {});
  const job = await createExport(appState.task.id, {
    formats,
    aurora_sections: selectedNarratives.map((item) => item.label),
    export_options: exportOptions,
  });
  setTask({...appState.task, export_jobs: [...(appState.task.export_jobs || []), job]});
  renderWorkflowProgress();
  renderProgress(formats, job.details?.artifacts || []);
  renderDownloads(job);
}

export function initExport() {
  renderSelectionCount();
  ensureSelectionCards();
  getRoots().done.style.display = "none";
  getRoots().progress.style.display = "none";
  window.toggleEx = (card) => {
    card.classList.toggle("on");
    renderSelectionCount();
  };
  window.runExport = runExport;
}
